name: Mi primer workflow
on: [push]  # Se ejecuta cuando haces un push al repositorio

jobs:
  saludar:
    runs-on: ubuntu-latest  # Sistema operativo de la máquina virtual
    steps:
      - name: Paso 1 - Hola mundo
        run: echo "¡Hola, GitHub Actions!"
      - name: Paso 2 - Todo bien Mundo
        run: echo "Jugando con Mundo!"
      - name: Paso 3 - Todo bien Mundo
        run: echo Jugando con Dos Mundo!"
      - name: Paso 4 - Todo bien Mundo
        run: echo "Jugando con Dos Mundo!"