name: Mi primer workflow

on: [push]  # Se ejecuta cuando haces push al repositorio

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Hola que tal"
      - run: echo "Fin"
  segundo_job:
    needs: primer_job
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: echo "Continuo luego del primero"
      - run: echo "Termine el Segundo"